tginet_C18/emfood/urls.py
from django.urls import path

from . import views

app_name = "emfood"
urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register, name="register"),
    path("share",views.share, name="share"), 
    path("share",views.sharefood, name="sharefood"),
    #path("", views.delete, name="delete"),
]

tginet_C18/tginet_C18/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("emfood/", include("emfood.urls")),
    path("admin/", admin.site.urls),
]

tginet_C18/emfood/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Emfood(models.Model):
    name = models.CharField(max_length=200)
    num = models.IntegerField()
    # 時刻あり期限
    expire_date = models.DateTimeField(blank=True, null=True)
    user=models.CharField(max_length=10, default="takahashi")
    # 時刻なし消費期限
    limit_date=models.DateField(blank=True, null=True )
    shere=models.BooleanField(default=False)

tginet_C18/emfood/forms.py
from django import forms
from .models import Emfood  # importに追加
from django.forms import widgets, NumberInput  # importに追加

class Emfoodadd(forms.ModelForm):
    class Meta:
        model = Emfood
        fields = ['name','num','limit_date','user']
        # expire_dateをプルダウン式に変更
        widgets = {
            'limit_date': NumberInput(attrs={'type': 'date'}),
            'user': widgets.HiddenInput()
        }
        labels = {
            'name': '非常食名',
            'num': '登録個数',
            'limit_date': '消費期限',
        }

tginet_C18/emfood/views.py
from django.shortcuts import render, redirect

from .models import Emfood
from .forms import Emfoodadd
from django.utils import timezone

def index(request):
    # expire_dateをlimit_dateに変更お願いします
    foodData = Emfood.objects.all().order_by('limit_date')
    header = ['ID', '非常食名', '保有数', '消費期限']
    todays_date = timezone.now().date()
    month_later_1 = todays_date + timezone.timedelta(days=30)
    # foodData内でtodays_dateよりもlimit_dateが前のものの個数をきろく
    outdata = 0
    for food in foodData:
        if food.limit_date < todays_date:
            outdata += 1
    month1_data = 0
    for food in foodData:
        if (food.limit_date < month_later_1) & (food.limit_date > todays_date):
            month1_data += 1
    my_dict = {
        'title': '保有非常食一覧',
        'header': header,
        'foodData': foodData,
        'now': todays_date,
        'month_later_1': month_later_1,
        'out': outdata,
        'near': month1_data,
    }
    return render(request, "emfood/index.html", my_dict)

def register(request):
    message = ''
    
    if(request.method == 'POST'):
        form = Emfoodadd(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='/emfood')
        else:
            message = '登録に失敗しました'
    
    modelform_dict = {
        'title': '非常食登録',
        'form': Emfoodadd(),
        'message': message,
    }
    return render(request, "emfood/register.html", modelform_dict)

# シェア一覧画面のメソッド
def share(request):
    foodData = Emfood.objects.filter(shere=1).order_by('limit_date')
    header = ['ID', '非常食名', '保有数', '消費期限']
    my_dict = {
        'title': '保有非常食一覧',
        'header': header,
        'foodData': foodData,
    }
    return render(request, "emfood/share.html", my_dict)

# index.htmlでシェアするボタンを押した時に動くメソッド
def sharefood(request, id):
    
    message = ''
    emfood_obj=Emfood.objects.get(id=id)
    if (request.method=='POST'):
        emfood_obj.shere=1
        emfood_obj.save()
    
    return render(request,"emfood/share")

def delete(request, id):
    header = ['ID', '非常食名', '保有数', '消費期限']
    message = ''
    emfood_obj = Emfood.objects.get(id=id)
    if (request.method == 'POST'):
        emfood_obj.delete()
        return redirect(to='/emfood')
    delete_dict = {
        'title': '削除画面',
        'header': header,
        'id': id,
        'emfood': emfood_obj,
        'message': message,
    }
    return render(request, "emfood/index.html", delete_dict)
    

tginet_C18/emfood/templates/emfood/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'emfood/style.css' %}">
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>EMFood</title>
        <meta name="keywords" content="ページのキーワードA,B,C">
        <meta name="description" content="ページの説明">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="outer">
            <header>
                <div id="header-container">
                    <div id="head-inner">
                        <h1>非常食管理アプリ　</h1>
                        <p class="description">～非常食管理とシェアの味方～</p>
                    </div>
                </div>
            </header>
            <div id="content-wrapper">
                <main>
                    {% if out > 0 %}
                        <h2 style='color: #bb0000;font-weight:bold;'>消費期限が切れた非常食が{{out}}件あります！！</h2>
                    {% endif %}
                    {% if near > 0 %}
                        <h2 style='color: #eedd22;font-weight:bold;'>消費期限が近い非常食が{{near}}件あります！！</h2>
                    {% endif %}
                </main>
                <p></p>
                <aside>
                    <h2>非常食一覧</h2>
                    <div class="food-list-head">
                        <div class='food-name'>食品名</div>
                        <div class='food-num'>個数</div>
                        <div class='food-ex'>消費期限</div>
                    </div>
                    {% for food in foodData %}
                        {% if 'takahashi' in food.user %}
                            {% if now > food.limit_date %} 
                                <div class="food-list" style="background: #bb0000">
                                    <div class='food-name'>{{ food.name }}</div>
                                    <div class='food-num'>{{ food.num}}</div>
                                    <div class='food-ex'>{{ food.limit_date }}</div>
                                </div>
                            {% elif month_later_1 > food.limit_date %}
                                <div class="food-list" style="background: #eedd22">
                                    <div class='food-name'>{{ food.name }}</div>
                                    <div class='food-num'>{{ food.num}}</div>
                                    <div class='food-ex'>{{ food.limit_date }}</div>
                                </div>
                            {% else %}
                                <div class="food-list">
                                    <div class='food-name'>{{ food.name }}</div>
                                    <div class='food-num'>{{ food.num}}</div>
                                    <div class='food-ex'>{{ food.limit_date }}</div>
                                    {% if food.shere != True %}
                                        <form action="{% url 'emfood:sharefood' %}" method="post">
                                            {% csrf_token %}
                                            <input type="submit" value="シェア">
                                        </form>
                                    {% else %}
                                        {% comment %} <input type="checkbox" name="shere"> {% endcomment %}
                                    {% endif %}
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    
                </aside>
                <div class="container">
                    <a href="./register" class="btn btn--orange register-btn">非常食の登録<a>
                    <a href="./share" class="btn btn--orange share-btn">シェア画面へ</a>
                </div>
            </div>
            <footer>© TGI C18</footer>
        </div>
    </body>
</html>

tginet_C18/emfood/templates/emfood/register.html
{% load static %}

<link rel="stylesheet" href="{% static 'emfood/style.css' %}">
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>EMFood</title>
        <meta name="keywords" content="非常食">
        <meta name="description" content="非常食の購入品を登録する">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="outer">
            <header>
                <div id="header-container">
                    <div id="head-inner">
                        <h1>非常食管理アプリ　</h1>
                        <p class="description">～非常食管理とシェアの味方～</p>
                    </div>
                </div>
            </header>
            <div id="content-wrapper">
                <aside>
                    <h2>登録内容</h2>
                </aside>
                {{ message }}
                <div class=centre>
                <table>
                    <form action="{% url 'emfood:register' %}" method="post">
                      {% csrf_token %}
                      {{ form.as_table }}
                      <tr>
                        <td></td>
                        <td>
                            <input type="submit"
                                value="送信"
                                class="btn btn--orange register-btn">
                        </td>
                      </tr>
                    </form>
                  </table>
                </div>
                <p></p>
            </div>
            <footer>© TGI C18</footer>
        </div>
    </body>
</html>

tginet_C18/emfood/templates/emfood/share.html
{% load static %}

<link rel="stylesheet" href="{% static 'emfood/style.css' %}">
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>EMFood</title>
        <meta name="keywords" content="ページのキーワードA,B,C">
        <meta name="description" content="ページの説明">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div id="outer">
            <header>
                <div id="header-container">
                    <div id="head-inner">
                        <h1>非常食管理アプリ　</h1>
                        <p class="description">～非常食管理とシェアの味方～</p>
                    </div>
                </div>
            </header>
            <div id="content-wrapper">
                <main>
                </main>
                <p></p>
                <aside>
                    <h2>非常食一覧</h2>
                    <div class="food-list-head">
                        <div class='food-name'>食品名</div>
                        <div class='food-num'>個数</div>
                        <div class='food-ex'>消費期限</div>
                        <div class='food-user'>オーナー</div>
                    </div>
                    {% for food in foodData %}
                    <div class="food-list">
                        <div class='food-name'>{{ food.name }}</div>
                        <div class='food-num'>{{ food.num}}</div>
                        <div class='food-ex'>{{ food.limit_date }}</div>
                        <div class='food-user'>{{ food.user }}</div>
                    </div>
                    {% endfor %}
                    
                </aside>
                <div class="container">
                    <a href="/emfood" class="btn btn--orange register-btn">もどる<a>
                    
                </div>
            </div>
            <footer>© TGI C18</footer>
        </div>
    </body>
</html>